---
 - name: Learning about blocks
   hosts: planetexpress

   tasks:
    - block:
       - name: Task 1
         shell: "echo 'My single task ran' > example.txt"
       - name: Task 2
         shell: "echo 'My second task ran' >> example.txt"
       - name: Task 3
         shell: "echo 'My third task ran' >> example.txt"
